services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: porfo-arkane
    restart: unless-stopped
    labels:
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.productivity-porto-ic9ptm-web.rule=Host(`arkane.my.id`)
      - traefik.http.routers.productivity-porto-ic9ptm-web.entrypoints=web
      - traefik.http.services.productivity-porto-ic9ptm-web.loadbalancer.server.port=3000
      - traefik.http.routers.productivity-porto-ic9ptm-web.service=productivity-porto-ic9ptm-web
      - traefik.enable=true
    networks:
      dokploy-network: {}
      default: {}

networks:
  dokploy-network:
    external: true
